global:
  scrape_interval: 10s
  scrape_timeout: 10s
   
scrape_configs:
  - job_name: 'webServer1'
    static_configs:
    - targets: ['webServer1:8080']

  - job_name: worker1
    scrape_interval: 30s
    scrape_timeout: 30s
    honor_labels: true
    static_configs:
      - targets: ['worker1:9091']