name: Release Drafter


on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        options:
          - patch
          - minor
        default: minor
        required: true
        description: 'patch: v0.0.X, minor: v0.X.0'
        
jobs:      
  publish_draft:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - uses: release-drafter/release-drafter@v5.12.1
          #with:
          #  name: "v2.4.0"
          #  tag: "v2.4.0"
          #  version: "v2.4.0"
          #  publish: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
